server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: INFO
    org.springframework: DEBUG

jwt:
  secret: "your-secret-key"
  expirationMs: 3600000
